[platformio]
default_envs = mega, esp32

[common_atmega]
platform  = atmelavr
framework = arduino
src_filter = +<atmega/>
monitor_speed = 115200
monitor_filters = colorize, time
lib_deps =
  adafruit/DHT sensor library @ ^1.4.6
  adafruit/Adafruit Unified Sensor @ ^1.1.14
  adafruit/RTClib @ ^2.1.4
  arduino-libraries/SD @ ^1.3.0

[env:mega]
extends     = common_atmega
board       = megaatmega2560
upload_port = /dev/ttyUSB0     ; change to your port (Windows: COM3)
build_flags =
  -DTARGET_MEGA
  -DSERIAL_DEBUG=1             ; full debug output on Mega

[env:atmega328p]
extends         = common_atmega
board           = uno           ; same Arduino core, different board target
upload_port     = /dev/ttyUSB1
upload_protocol = arduino
build_flags =
  -DTARGET_328P
  -DSERIAL_DEBUG=0             ; debug prints removed → saves flash/RAM

[env:esp32]
platform  = espressif32 @ ^6.5.0
board     = esp32dev
framework = arduino
src_filter = +<esp32/>

lib_deps =
  mikalhart/TinyGPSPlus @ ^1.0.3
  knolleary/PubSubClient @ ^2.8.0
  ESP32Async/ESPAsyncWebServer @ ^3.6.0
  ESP32Async/AsyncTCP @ ^3.3.2
